#!/usr/bin/bash

BASEDIR="$PWD"
URL=""
FORCE=0

move_file()
{
    test -f "$1" || return 1
    echo "cmd  : chmod +x ${filepath}"
    chmod +x "$filepath"
    echo "cmd  : mv ${filepath} /usr/local/bin/"
    mv "$filepath" /usr/local/bin/
}

while (($#)); do
    case "$1" in
        -f)
        FORCE=1
        ;;
        *)
        URL="$1"
        ;;
    esac
    shift
done

if [[ $URL != "http"* ]]; then
    echo "usage : appinst \"https://url/to/program\""
    echo "usage : appinst -f \"https://url/to/program\""
    echo "abort..."
    exit 1
fi

if [[ "$EUID" != 0 ]]; then
    echo "*** needs sudo"
    echo "abort..."
    exit 1
fi

if [[ ! -f /usr/bin/wget ]]; then
    echo "*** wget not found"
    echo "install it with :"
    echo "sudo apt install wget"
    echo "abort..."
    exit 1
fi

filename=$(basename "$URL")
filepath=${BASEDIR}/${filename}

if [[ ! -f $filepath ]]; then
    wget "$URL"
fi

if [[ ! -f $filepath ]]; then
    echo "*** download error"
    echo "abort..."
    exit 1
fi

echo "file : $filepath"

filetype=$(file -b "$filepath")
echo "type : $filetype"

if [[ $FORCE != 1 ]] \
&& [[ $filetype != "ELF"* ]] \
&& [[ $filetype != "Bourne-Again shell script"* ]]; then
    echo "*** file is not an ELF file or a bash script"
    echo "abort..."
    exit 1
fi

move_file "$filepath"


