#!/usr/bin/bash

basedir="$PWD"
url=""
destdir="$HOME/.local/bin/"
force=0

move_file()
{
    test -f "$1" || return 1
    test -d "$2" || mkdir -p "$2"
    echo "cmd  : chmod +x ${1}"
    chmod +x "$1"
    echo "cmd  : mv ${1} ${2}"
    mv "$1" "$2"
}

while (($#)); do
    case "$1" in
        -f)
        force=1
        ;;
        *)
        url="$1"
        ;;
    esac
    shift
done

if [[ "$EUID" == 0 ]]; then
    destdir="/usr/local/bin/"
fi

if [[ $url != "http"* ]]; then
    echo "usage : appinst \"https://url/to/a_file\""
    echo "usage : appinst -f \"https://url/to/a_file\""
    echo "abort..."
    exit 1
fi

if [[ $url == *"/" ]]; then
    echo "*** url must point to a file such as :"
    echo "\"https://url/to/a_file\""
    echo "abort..."
    exit 1
fi

if [[ ! -f /usr/bin/wget ]]; then
    echo "*** wget not found"
    echo "install it with :"
    echo "sudo apt install wget"
    echo "abort..."
    exit 1
fi

filename=${url##*/}
filepath=$basedir/$filename

test -f "$filepath" || wget "$url"

if [[ ! -f $filepath ]]; then
    echo "*** download error"
    echo "abort..."
    exit 1
fi

echo "file : $filepath"

filetype=$(file -b "$filepath")
echo "type : $filetype"

if [[ $force != 1 ]] \
&& [[ $filetype != "ELF"* ]] \
&& [[ $filetype != "Bourne-Again shell script"* ]] \
&& [[ $filetype != "Python script"* ]] \
&& [[ $filetype != "Perl script"* ]]; then
    echo "*** file is not an ELF file or a bash script"
    echo "abort..."
    exit 1
fi

move_file "$filepath" "$destdir"


