#!/usr/bin/bash

apt_update()
{
    dest=/tmp/uptest
    val=0
    trigger=900

    if [[ -f $dest ]];then
        val=$(< $dest)
    fi

    current=$(date +%s)
    diff=$(expr $current - $val)
    ret=1

    if [ $diff -gt $trigger ]; then
        ret=0
        sudo apt update
    fi

    date +%s > /tmp/uptest
    
    return $ret
}

while [[ $# > 0 ]]; do
    key="$1"
    case $key in
        dist)
        apt_update
        sudo apt dist-upgrade
        exit 0
        ;;
        full)
        apt_update
        sudo apt full-upgrade
        exit 0
        ;;
        *)
        echo "invalid option"
        echo "abort..."
        exit 1
        ;;
    esac
    shift
done

apt_update
sudo apt upgrade


