#!/usr/bin/bash

apt_update()
{
    dest=/tmp/uptest
    val=0
    trigger=900

    if [[ -f $dest ]];then
        val=$(< $dest)
    fi

    current=$(date +%s)
    diff=$(expr $current - $val)
    ret=1

    if [ $diff -gt $trigger ]; then
        ret=0
        sudo apt update
    fi

    date +%s > /tmp/uptest
    
    return $ret
}

if [[ $# > 1 ]]; then
    echo "too much parameters"
    echo "abort..."
    exit 1
fi

if [[ $# == 0 ]]; then
    echo "apt upgrade..."
    apt_update
    sudo apt upgrade
    exit 0
fi

case $1 in
    full)
    echo "apt full-upgrade..."
    apt_update
    sudo apt full-upgrade
    exit 0
    ;;
    *)
    echo "invalid option"
    echo "abort..."
    exit 1
    ;;
esac


