#!/usr/bin/bash

appname=${0##*/}

error_exit()
{
    msg="$1"
    test "$msg" != "" || msg="an error occurred"
    printf "*** $msg\nabort...\n"
    exit 1
}

usage_exit()
{
    echo "*** usage :"
    echo "$appname /path/to/file"
    echo "sudo $appname /path/to/file"
    echo "abort..."
    exit 1
}

test "$#" -gt 0 || usage_exit

opt_filepath=""
opt_unbak=0
opt_mode="cp"
opt_force=0

while (($#)); do
    case "$1" in
        -u)
            opt_unbak=1
        ;;
        -m)
            opt_mode="mv"
        ;;
        -f)
            opt_force=1
        ;;
        *)
            test "$opt_filepath" == "" || usage_exit
            opt_filepath="$1"
        ;;
    esac
    shift
done

file_backup()
{
    local src="$1"
    local dest="$2"
    local mode="$3"
    local force=$4
    
    if [[ ! -f "$src" ]] && [[ ! -d "$src" ]]; then
        error_exit "$src doesn't exist"
    fi
    
    if [[ -f "$dest" ]] || [[ -d "$dest" ]]; then
        if [[ $force == 1 ]]; then
            echo "rm -rf $dest"
            rm -rf "$dest"
        else
            echo "dest file exists"
            return
        fi
    fi
    
    if [[ "$mode" == "cp" ]]; then
        echo "cp $src $dest"
        cp -r "$src" "$dest"
    elif [[ "$mode" == "mv" ]]; then
        echo "mv $src $dest"
        mv "$src" "$dest"
    else
        error_exit "file_backup: invalid mode"
    fi
}

filepath=$(echo "$opt_filepath" | sed 's:/*$::')
filename="${filepath%.*}"
ext="${filepath##*.}"

if [[ "$ext" == "bak" ]]; then
    src="${filename}.bak"
    dest="$filename"
    opt_mode="mv"
elif [[ "$opt_unbak" -eq 1 ]]; then
    src="${filename}.bak"
    dest="$filename"
    opt_mode="mv"
else
    src="$filepath"
    dest="${filepath}.bak"
fi

#echo "$src $dest $opt_mode $opt_force"
file_backup "$src" "$dest" "$opt_mode" $opt_force


