#!/usr/bin/bash

# usage : cbuild <target> <file1.c file2.c>  <lib1 lib2>
# example : cbuild test file.c gtk+-3.0

TARGET=""
CFLAGS="-Wall -Wextra -O2 -D_GNU_SOURCE"
SOURCES=""
LIBS=""

get_arg()
{
    arg="$1"
    ext="${arg##*.}"
    if [[ $arg == -* ]]; then
        CFLAGS+=" "
        CFLAGS+="$arg"
    elif [[ $ext == "c" ]]; then
        if [[ $SOURCES != "" ]]; then
            SOURCES+=" "
        fi
        SOURCES+="$arg"
    elif [[ $SOURCES == "" ]]; then
        TARGET="$arg"
    else
        if [[ $LIBS != "" ]]; then
            LIBS+=" "
        fi
        LIBS+="$arg"
    fi
}

while [[ $# > 0 ]]; do
    arg="$1"
    case $arg in
        *)
        get_arg $arg
        shift
        ;;
    esac
done

if [[ $LIBS != "" ]]; then
    echo "gcc $CFLAGS -o $TARGET $SOURCES $(pkg-config --cflags --libs $LIBS)"
    gcc $CFLAGS -o $TARGET $SOURCES $(pkg-config --cflags --libs $LIBS)
else
    echo "gcc $CFLAGS -o $TARGET $SOURCES"
    gcc $CFLAGS -o $TARGET $SOURCES
fi


