#!/usr/bin/bash

# example : cbuild test file.c gtk+-3.0

appname=${0##*/}
opt_target=""
opt_cflags="-Wall -Wextra -O2 -D_GNU_SOURCE"
opt_sources=""
opt_libs=""

usage_exit()
{
    echo "*** usage :"
    echo "$appname target file1.c file2.c lib1 lib2"
    echo "example : $appname test file.c gtk+-3.0"
    echo "abort..."
    exit 1
}

get_arg()
{
    arg="$1"
    ext="${arg##*.}"
    if [[ $arg == -* ]]; then
        test -z "$opt_cflags" || opt_cflags+=" "
        opt_cflags+="$arg"
    elif [[ $ext == "c" ]]; then
        test -z "$opt_sources" || opt_sources+=" "
        opt_sources+="$arg"
    elif [[ $opt_sources == "" ]]; then
        opt_target="$arg"
    else
        test -z "$opt_libs" || opt_libs+=" "
        opt_libs+="$arg"
    fi
}

test "$#" -gt 1 || usage_exit

while (($#)); do
    case "$1" in
        *)
        get_arg "$1"
        ;;
    esac
    shift
done

if [[ $opt_libs != "" ]]; then
    echo "gcc $opt_cflags -o $opt_target $opt_sources $(pkg-config --cflags --libs $opt_libs)"
    gcc $opt_cflags -o "$opt_target" $opt_sources $(pkg-config --cflags --libs $opt_libs)
else
    echo "gcc $opt_cflags -o $opt_target $opt_sources"
    gcc $opt_cflags -o "$opt_target" $opt_sources
fi


