#!/bin/bash

T='Three can keep a secret, if two of them are dead.'

for FGs in '  30m' '1;30m' '  31m' '1;31m' \
           '  32m' '1;32m' '  33m' '1;33m' \
           '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m';
  do FG=${FGs// /}
  echo -e "\033[$FG $T \033[0m"
done


