#!/usr/bin/bash

mdconvert()
{
    if [[ "${1: -3}" != ".md" ]]; then
        echo "*** wrong file type : $1"
        return
    fi

    inpath=$1
    outpath=${inpath%.md}.html
    opts="--html --tables --fenced-code --autolink --strikethrough --disable-intra-emphasis"

    echo "convert : $1"
    
    hoedown $opts $inpath > $outpath
}

mdparse()
{
    if [[ ! -d $1 ]]; then
        echo "*** wrong directory : $1"
        return
    fi

    for file in $1/*.md; do
        if [[ -f $file ]]; then
            mdconvert $file
        fi
    done
}

if [[ $# == 0 ]]; then
    mdparse $PWD
    exit 0
elif [[ $# == 1 ]]; then
    if [[ -d $1 ]]; then
        mdparse $1
        exit 0
    elif [[ -f $1 ]]; then
        mdconvert $1
        exit 0
    fi
fi

echo "usage: mdconv"
echo "usage: mdconv file.md"
echo "usage: mdconv directory"
exit 1


