#!/usr/bin/bash

appname=${0##*/}
radios="$HOME/.radios"

opt_volume=50
opt_af=

error_exit()
{
    msg="$1"
    test "$msg" != "" || msg="an error occurred"
    printf "*** $msg\nabort...\n"
    exit 1
}

usage_exit()
{
    echo "*** usage :"
    echo "$appname -list"
    echo "$appname -add \"name\" \"https://my/radio/stream\""
    echo "$appname -show \"name\""
    echo "$appname -remove \"name\""
    echo "$appname \"name\""
    echo "$appname \"https://my/radio/stream\""
    echo "$appname \"path/to/file.mp3\""
    echo "$appname -stop"
    echo "abort..."
    exit 1
}

add_file()
{
    filepath="$radios/$1"
    printf "url=$2\n" > "$filepath"
}

play_file()
{
    opt_url=""
    if [[ -f "$1" ]]; then
        opt_url="$1"
    elif [[ "$1" == "http://"* ]] || [[ "$1" == "https://"* ]]; then
        opt_url="$1"
    else
        filepath="$radios/$1"
        test -f "$filepath" || error_exit "invalid file"
        parse_file "$filepath"
    fi
    cmd="ffplay -nodisp -volume $opt_volume"
    if [[ $opt_af != "" ]]; then
        cmd+=" -af \"$opt_af\""
    fi
    cmd+=" $opt_url"
    cmd+=" > /dev/null 2>&1"
    cmd+=" &"
    
    pkill ffplay
    echo "$cmd"
    eval "$cmd"
}

parse_file()
{
    IFS="="
    while read -r key val; do
        value=${val//\"/}
        case "$key" in
            af)
                opt_af="$value"
            ;;
            volume)
                opt_volume="$value"
            ;;
            url)
                opt_url="$value"
            ;;
            *)
            ;;
        esac
    done < "$1"
}

probe_file()
{
    echo "infos: $1"
    filepath="$radios/$1"
    test -f "$filepath" || error_exit "invalid file"
    opt_url=""
    parse_file "$filepath"
    ffprobe -hide_banner "$opt_url"
}

test -d "$radios" || mkdir -p "$radios"
test "$#" -gt 0 || usage_exit

while (($#)); do
    case "$1" in
        -add)
            add_file "$2" "$3"
            exit 0
        ;;
        -infos)
            test "$#" -eq 2 || usage_exit
            probe_file "$2"
            exit 0
        ;;
        -list)
            ls -la "$radios"
            exit 0
        ;;
        -remove)
            test "$#" -eq 2 || usage_exit
            rm "$radios/$2"
            exit 0
        ;;
        -show)
            test "$#" -eq 2 || usage_exit
            cat "$radios/$2"
            echo
            exit 0
        ;;
        -volume)
            test "$#" -gt 1 || usage_exit
            shift
            opt_volume="$1"
        ;;
        -stop)
            pkill ffplay
            exit 0
        ;;
        *)
            play_file "$1"
            exit 0
        ;;
    esac
    shift
done


