#!/usr/bin/bash

appname=${0##*/}
radios="$HOME/.radios"

error_exit()
{
    msg="$1"
    test "$msg" != "" || msg="an error occurred"
    printf "*** $msg\nabort...\n"
    exit 1
}

play_file()
{
    local url=""
    if [[ "$1" == "http://"* ]] || [[ "$1" == "https://"* ]]; then
        url="$1"
    else
        filepath="$radios/$1"
        test -f "$filepath" || error_exit "invalid file"
        url=$(head -n 1 "$filepath")
    fi
    pkill ffplay
    ffplay -nodisp -volume 40 "$url" > /dev/null 2>&1 &
}

test -d "$radios" || mkdir -p "$radios"

if [[ "$#" -eq 0 ]]; then
    pkill ffplay
    exit 0
fi

while (($#)); do
    case "$1" in
        -list)
            ls -la "$radios"
            exit 0
        ;;
        *)
            play_file "$1"
            exit 0
        ;;
    esac
    shift
done


