#!/usr/bin/bash

if [[ $# != 2 ]]; then
    echo "usage:" >&2
    echo "lsblk to find witch device and partition" >&2
    echo "umount to unmount partitions" >&2
    echo "" >&2
    echo "example:" >&2
    echo "lsblk" >&2
    echo "sudo umount /dev/sdb1" >&2
    echo "rpimg /path/my_file.img /dev/sdb" >&2
    exit 1
fi

basedir="$(dirname "$0")"
. "$basedir/libshell"

inpath=$1
outpath=$2

if [[ ! -f $inpath ]] || [[ $inpath != *.img ]]; then
    echo file error
    exit 1
fi

echo sudo dd if=$inpath of=$outpath bs=4M conv=fsync status=progress

confirm || abort

sudo dd if="$inpath" of="$outpath" bs=4M conv=fsync status=progress


