#!/usr/bin/bash

# -----------------------------------------------------------------------------

confirm()
{
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [Y/n]} " response
    case "$response" in
        [yY][eE][sS]|[yY]|"") 
            true
            ;;
        *)
            false
            ;;
    esac
}

abort()
{
    echo "${1:-abort}"
    exit 1
}

# -----------------------------------------------------------------------------

basedir="$(dirname "$0")"

inpath=$1
outpath=$2

if [[ $# != 2 ]]; then
    echo "usage:" >&2
    echo "extract the image if compressed" >&2
    echo "run lsblk to find the target device" >&2
    echo "umount all partitions" >&2
    echo "" >&2
    echo "example on /dev/sdc :" >&2
    echo "unxz /path/my_file.img.xz" >&2
    echo "lsblk" >&2
    echo "umount /dev/sdc?" >&2
    echo "rpimg /path/my_file.img /dev/sdc" >&2
    exit 1
fi

if [[ ! -f $inpath ]]; then
    echo "input file error"
    exit 1
fi

echo sudo dd if=$inpath of=$outpath bs=4M conv=fsync status=progress

confirm || abort

sudo dd if=/dev/zero of="$outpath" bs=512 count=1 conv=notrunc
sync
sudo dd if="$inpath" of="$outpath" bs=4M conv=fsync status=progress
sync

