#!/usr/bin/bash

basedir="$(dirname "$0")"
. "$basedir/libshell"

inpath=$1
outpath=$2

if [[ ! -f $inpath ]] || [[ $inpath != *.img ]]; then
    echo file error
    exit 1
fi

echo sudo dd if=$inpath of=$outpath bs=4M conv=fsync status=progress

confirm || abort

sudo dd if="$inpath" of="$outpath" bs=4M conv=fsync status=progress


