#!/usr/bin/bash

if [[ $# != 1 ]]; then
    echo "usage:" >&2
    echo "testdd /tmp/outfile.img" >&2
    exit 1
fi

outpath=$1

# write
dd if=/dev/zero of="$outpath" bs=1G count=1 oflag=dsync

# read
echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null
dd if="$outpath" of=/dev/null bs=8k

# cached
dd if="$outpath" of=/dev/null bs=8k


