#!/usr/bin/env python3

import sys, os, subprocess

basedir=os.getcwd()

argv=sys.argv
argc=len(argv)
count=argc

if argc < 2:
    print("generate supp file : vrun -gen appname")
    print("execute program    : vrun appname")
    exit(1)

appname=""
generate=False

while count > 1:
    arg=argv[count-1]
    if arg == "-gen":
        generate=True
    else:
        appname=arg
    count-=1

exepath=os.path.join(basedir, appname)
logpath=exepath + ".log"
outpath=exepath + ".supp"

cmd = ["valgrind", 
       "--leak-check=full",
       "--show-leak-kinds=definite",
       "--num-callers=20",
       "--suppressions=/usr/share/glib-2.0/valgrind/glib.supp",
       "--suppressions=/usr/share/gtk-3.0/valgrind/gtk.supp",
]

if generate:
    cmd += ["--gen-suppressions=all",
            "--log-file=" + logpath,
    ]
    
cmd += [exepath]

print(" ".join(cmd))

subprocess.run(cmd)

if generate:
    infile=open(logpath, "r")
    outfile=open(outpath, "w")

    for line in infile.readlines():
        if not line.startswith("=="):
            outfile.write(line)

    infile.close()
    outfile.close()


