#!/usr/bin/bash

appname=${0##*/}
wallpapers="$HOME/.backgrounds"
current="$HOME/.wallpaper"
opt_random=0
newname=""
filepath=""

usage_exit()
{
    echo "*** usage :"
    echo "$appname \"/path/to/file.jpg\""
    echo "$appname -random"
    echo "$appname -save \"file_name\""
    echo "$appname -set \"file_name\""
    echo "$appname -parse"
    echo "$appname -list"
    echo "abort..."
    exit 1
}

error_exit()
{
    printf "$1\n"
    echo "abort..."
    exit 1
}

wallpaper_set()
{
    if [[ $1 == "http"* ]]; then
        wget -O "$current" "$1"
        hsetroot -cover "$current"
        exit 0
    fi
    
    test -f "$1" || error_exit "invalid file : $1"
    cp "$1" "$current"
    hsetroot -cover "$current"
}

test -d "$wallpapers" || mkdir -p "$wallpapers"

while (($#)); do
    case "$1" in
        -parse)
            viewnior "$wallpapers" &
            exit 0
        ;;
        -random)
            opt_random=1
        ;;
        -save)
            test $# -gt 1 || error_exit "*** missing option"
            shift
            newname="$1"
        ;;
        -set)
            test $# -gt 1 || error_exit "*** missing option"
            shift
            filepath="$wallpapers/$1"
        ;;
        -list)
            ls -l "$wallpapers/"; exit 0
        ;;
        *)
            test "$filepath" == "" || usage_exit
            filepath="$1"
        ;;
    esac
    shift
done

if [[ "$newname" != "" ]]; then
    echo "save : \"$newname\""
    cp "$HOME/.wallpaper" "$wallpapers/$newname"
    exit 0
fi

if [[ $opt_random == 1 ]]; then
    wallpaper_set "https://picsum.photos/1680/1050?random"
    exit 0
fi

if [[ "$filepath" == "" ]]; then
    usage_exit
fi

wallpaper_set "$filepath"


