#!/usr/bin/bash

wallpapers="$HOME/.backgrounds"
current="$HOME/.wallpaper"
save=0
newname=""
filepath=""

wallpaper_set()
{
    if [[ $1 == "http"* ]]; then
        wget -O "$current" "$1"
        hsetroot -cover "$current"
    elif [[ -f $1 ]]; then
        cp "$1" "$current"
        hsetroot -cover "$current"
    fi
}

while (($#)); do
    case "$1" in
        -save)
        save=1
        test $# -gt 0 && shift; newname="$1"
        ;;
        *)
        filepath="$1"
        ;;
    esac
    shift
done

test -d "$wallpapers" || mkdir -p "$wallpapers"

if [[ save == 1 ]]; then
    if [[ $newname == "" ]]; then
        exit 1
    fi
    cp "$HOME/.wallpaper" "$wallpapers/$newname"
    exit 0
fi

if [[ $filepath != "" ]]; then
    wallpaper_set "$filepath"
else
    wallpaper_set "https://unsplash.it/1680/1050?random"
fi


