#!/usr/bin/bash

wallpapers="$HOME/.backgrounds"
current="$HOME/.wallpaper"
save=0
newname=""
filepath=""

wallpaper_set()
{
    if [[ $1 == "http"* ]]; then
        wget -O "$current" "$1"
        hsetroot -cover "$current"
    elif [[ -f $1 ]]; then
        cp "$1" "$current"
        hsetroot -cover "$current"
    fi
}

usage_exit()
{
    echo "*** usage :"
    echo "wallset"
    echo "wallset \"my_file.jpg\""
    echo "wallset -save \"my_file.jpg\""
    exit 1
}

test -d "$wallpapers" || mkdir -p "$wallpapers"

while (($#)); do
    case "$1" in
        -save)
            save=1
            test $# -gt 0 && shift; newname="$1"
        ;;
        *)
            test "$filepath" == "" || usage_exit
            filepath="$1"
        ;;
    esac
    shift
done

if [[ $save == 1 ]]; then
    test "$newname" != "" || usage_exit
    echo "save : \"$newname\""
    cp "$HOME/.wallpaper" "$wallpapers/$newname"
    exit 0
fi

if [[ $filepath != "" ]]; then
    wallpaper_set "$filepath"
else
    wallpaper_set "https://picsum.photos/1680/1050?random"
fi


