#!/usr/bin/env python3
# https://pynative.com/python-rename-file/
import os, sys, re

n = len(sys.argv)
folder = ""

if n != 2:
    folder = os.getcwd()
else:
    folder = sys.argv[1]

if not os.path.isdir(folder):
    print("invalid directory...")
    print("abort...")
    sys.exit(1)

for fname in sorted(os.listdir(folder)):
    name, ext = os.path.splitext(fname)
    if not name.endswith("]"):
        continue
    newname = ""
    for c in name:
        if c == "[":
            if newname == "":
                break
            newname = newname.strip()
            name += ext
            newname += ext
            path = os.path.join(folder, name)
            newpath = os.path.join(folder, newname)
            print(path)
            print(newpath)
            os.rename(path, newpath)
            break
        newname += c


